# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b67fb96acaa0a92a641a2c0f7381f6d5613a16b7bf9212e993deefec2d6d0435bca5a7e4686beccf3f4beb01b81853b340666e32fa7b8e3cd9600386ec5c1a

test:
  secret_key_base: cfa3e01480649ecd10c9a50f08c3e6166beec45f9f7a066f4455d4e066f862d30af95025be4bdb3be95343e33afd60738e4824adc041b0a3862761c55c448791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
